services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - PORT=4000
    volumes:
      - uploads:/app/uploads
    depends_on:
      - mongo

volumes:
  mongo-data:
  uploads:
